### ISSUE TITLE
msm angle error

### ISSUE THREAD

**Issue by AdebayoBraimah** [ecr05/MSM_HOCR#11]
Hi,

I am a little unsure of where to start with an issue like this.

I am running MSM with neonatal surface data generated from the dHCP pipeline and trying to register each hemisphere of the surface data to 32k mesh spheres from https://brain-development.org/brain-atlases/atlases-from-the-dhcp-project/cortical-surface-atlas-bozek/. The config files I am using are the `MSMSulcStrainFinalconf`.

Some registrations work as intended, however, some registrations fail. Here is an example error:
```
terminate called after throwing an instance of 'NEWMESH::NEWMESHException'
  what():   newmesh::update_RELATIONS_for_ind::() angle error
/usr/local/bin/jobstarter: line 28: 15098 Aborted                 (core dumped) /scratch/brac4g/IRC317H/BIDS/derivatives/cifti_reg/msm/msm \
--conf=/scratch/brac4g/IRC317H/BIDS/derivatives/cifti_reg/msm/config/HCP_multimodal_alignment/MSMSulcStrainFinalconf \
--inmesh=/scratch/brac4g/IRC317H/BIDS/derivatives/dHCP_surf_recon_resampled_0.5mm/derivatives/sub-C11/ses-001/anat/Native/sub-C11_ses-001_right_sphere.surf.gii \
--out=C11-001.R.MSMsulc. --refmesh=/scratch/brac4g/IRC317H/BIDS/derivatives/cifti_reg/templateDHCP/dHCP.week44.R.sphere.surf.gii \
--refdata=/scratch/brac4g/IRC317H/BIDS/derivatives/cifti_reg/templateDHCP/dHCP.week44.R.sulc.shape.gii \
--indata=/scratch/brac4g/IRC317H/BIDS/derivatives/dHCP_surf_recon_resampled_0.5mm/derivatives/sub-C11/ses-001/anat/Native/sub-C11_ses-001_right_sulc.shape.gii \
--format=GIFTI \
--verbose
```

I was wondering if an issue like this has come up before, and if so, is there anything that I could do on my end to remedy the issue?

Best,

----

edit: output error formatting for readability.

**Comment by ecr05** [comment]
Hi the short answer is yes it has come up before. The long answer is I would probably need to see your data to see what is going wrong. It sounds like something might be wrong with one of your meshes - have you checked them?

Tbh for issues such as this which are more implementation related than code related it might be better to post of the FSL list such that others can later benefit.

Either way if you would like to send the files for this I will try and work it out.

**Comment by AdebayoBraimah** [comment]
[files.zip](https://github.com/ecr05/MSM_HOCR/files/3833248/files.zip)

I did not check my meshes (at least not closely). Some spheres seem to have a strange semi-sphere appearance in workbench. That's likely the culprit.

I included the files to reproduce the issue. Thanks.

**Comment by ecr05** [comment]
Yes, this is the issue - the surface pipeline failed for this dataset - probably a problem for the dHCP neurostars list

Thanks

**Comment by AdebayoBraimah** [comment]
Understood.

Thanks @ecr05
