### ISSUE TITLE
Makefile:2: /default.mk: No such file or directory Error

### ISSUE THREAD

**Issue by hspopal** [ecr05/MSM_HOCR#12]
Hello,

I am having an issue with the Makefile compilation step. I am getting the following error:

```
~/Downloads/MSM_HOCR-master/src/DiscreteOpt$ make
Makefile:2: /default.mk: No such file or directory
make: *** No rule to make target '/default.mk'.  Stop.
```

I am using a linux with Ubuntu 18.04 and fsl6. Not sure what else would be help to know in order to troubleshoot this. Thanks for your help.

**Comment by ecr05** [comment]
Have you got your FSL environment variables set up correctly?

**Comment by hspopal** [comment]
I believe so. I have the FSLDEVDIR set up with the FastPDlib copied from $FSLDIR/src
`~/Downloads/MSM_HOCR-master/src/DiscreteOpt$ echo $FSLDEVDIR 
/usr/local/msm
`

`~/Downloads/MSM_HOCR-master/src/DiscreteOpt$ ls $FSLDEVDIR/extras/src
FastPDlib
`

And then I have the ELC directory copied from the github repository
`~/Downloads/MSM_HOCR-master/src/DiscreteOpt$ ls $FSLDEVDIR/extras/include
ELC
`

**Comment by ecr05** [comment]
The problem is that it cannot find the FSLDIR/config. Try typing echo $FSLCONFDIR. Assumedly it comes back with nothing?

It's not the FSLDEV you need it is the FSLDIR. Where is your FSL installed? I always install FSL from source but a binary install might be ok if it provides all the necessary header files and libraries.  However, that is more of a question for the FSL list.

**Comment by hspopal** [comment]
I believe that worked, but now I am getting a permissions issue. When I try to run the make command with sudo, the original issue comes back.

`(base) tuk12127@cla27562:/usr/local/msm/extras/src/DiscreteOpt$ make
/usr/local/fsl/config/common/rules.mk:320: depend.mk: No such file or directory
Building dependency file depend.mk
touch: cannot touch 'depend.mk': Permission denied
/bin/sh: 3: cannot create depend.mk: Permission denied
/bin/sh: 3: cannot create depend.mk: Permission denied
/bin/sh: 3: cannot create depend.mk: Permission denied
/bin/sh: 3: cannot create depend.mk: Permission denied
/bin/sh: 3: cannot create depend.mk: Permission denied
touch: cannot touch 'depend.mk': Permission denied
touch: cannot touch 'depend.mk': Permission denied
touch: cannot touch 'depend.mk': Permission denied
/usr/local/fsl/config/common/rules.mk:311: recipe for target 'depend.mk' failed
make: *** [depend.mk] Error 1
(base) tuk12127@cla27562:/usr/local/msm/extras/src/DiscreteOpt$ sudo make
Makefile:2: /default.mk: No such file or directory
make: *** No rule to make target '/default.mk'.  Stop.`

**Comment by ecr05** [comment]
It doesn't look like it worked.  Also you are trying to build in your /usr/local for which you shouldn't have write permissions. 

You don't need to install anyway. There are binaries available from the release tab.
