### ISSUE TITLE
fatal error: newmatap.h: No such file or directory

### ISSUE THREAD

**Issue by ShacharGal** [ecr05/MSM_HOCR#14]
while trying to compile MSM_HOCR on ubuntu 18.04 we encountered this error:

root@maestro:/MSM_HOCR/src/DiscreteOpt# make
c++ -Wall -ansi -pedantic    -g -DNDEBUG -std=c++11  -DHAS_HOCR  -DNDEBUG  -O3 -fexpensive-optimizations  -I/usr/local/fsl/extras/include/boost -I/usr/local/fsl/extras/include/newmat -I/usr/local/fsl/extras/include/newran -I/usr/local/fsl/extras/include -I/usr/local/fsl/extras/include/libcprob -I/usr/local/fsl/extras/include/libprob -I/usr/local/fsl/extras/include/boost -I/usr/local/fsl/MSM_HOCR/include -I/usr/local/fsl/MSM_HOCR/extras/include -I. -I/usr/local/fsl/MSM_HOCR/include -I/usr/local/fsl/include   -c -o DiscreteCostFunction.o DiscreteCostFunction.cpp
In file included from /usr/local/fsl/include/newmesh/resampler.h:104:0,
                 from /usr/local/fsl/include/newmesh/meshfns.h:72,
                 from /usr/local/fsl/include/newmesh/featurespace.h:77,
                 from similarities.h:17,
                 from DiscreteCostFunction.h:9,
                 from DiscreteCostFunction.cpp:8:
**/usr/local/fsl/include/utils/log.h:85:10: fatal error: newmatap.h: No such file or directory**
 #include "newmatap.h"
          ^~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'DiscreteCostFunction.o' failed
make: *** [DiscreteCostFunction.o] Error 1
root@maestro:/MSM_HOCR/src/DiscreteOpt#

any ideas on how to complete this compilation? or alternative solutions for getting the updated msm binary for usage with MSMAll?

thanks

**Comment by ecr05** [comment]
This is probably a FSL v5 versus v6 issue? These files are not present in FSLv6 but the new master should work
