### ISSUE TITLE
newmesh missing in 'master' and 'FSL' branches?

### ISSUE THREAD

**Issue by RyanDMarshall** [ecr05/MSM_HOCR#15]
The src/newmesh directory seems to have disappeared in the 'master' and 'FSL' branches, but compilation instructions still lists needing to compile newmesh before anything else. What should I do? :)

**Comment by ecr05** [comment]
Hi, for FSLv6 the FSL newmesh library is up to date with the MSM one so you don't need the one from this repo. You are completely correct that I need to update the compilation instructions. I will do that now.

By the way, if you have a mac/ubuntu or centos system you should just be able to use the binaries from the release tab https://github.com/ecr05/MSM_HOCR/releases
