### ISSUE TITLE
install MSM with fsl 6 on Mac

### ISSUE THREAD

**Issue by renxili** [ecr05/MSM_HOCR#16]
Hi, just wondering how we should install MSM on Mac, since fsl 6 is now installed via a python installer, which means there is no software package for us to download. How should we add the binary?

**Comment by ecr05** [comment]
Just take the binary and put it in the fsl/src/MSM folder of your fsl installations

**Comment by renxili** [comment]
For Mac, should we put the "msm_mac_v3" in fsl/src/MSM? Do we need to extract "msm_mac_v3"? Also, what about the files that are already in fsl/src/MSM?

**Comment by ecr05** [comment]
You need to rename it msm to overwrite the msm binary in fsl/src/MSM. If you want to keep the old one then move it somewhere else or rename it msm_fsl

**Comment by renxili** [comment]
Thank you so much! It turns out that FLS 6.0.3 did not add executable files to $FSLDIR/bin directory so MSM was not running on my computer!
