### ISSUE TITLE
--regoption: Option doesn't exist!

### ISSUE THREAD

**Issue by sameera2004** [ecr05/MSM_HOCR#17]
Hi,

I am using HCP pipeline 4.2 to process our fMRI data. I am getting above error (--regoption: Option doesn't exist!) when I am trying to use "MSMSulc" for the surface registration. I didn't see any issue when I am using " FS" option. I followed all the steps in "MSM_HOCR/compilation instructions" to compile. Below, please find the PostFreeSurfer - error file. 

reading colortable from annotation file...
colortable with 36 entries read (originally /autofs/space/tanha_002/users/greve/fsdev.build/average/colortable_desikan_killiany.txt)
reading colortable from annotation file...
colortable with 76 entries read (originally Simple_surface_labels2008.txt)

WARNING: input sphere is either unusually irregular or not centered, inspect the input

Part of FSL (ID: 6.0.3:b862cdd5)
msm configuration parameters

Usage:

Optional arguments (You may optionally specify one or more of):
        --opt   optimisation method. Choice of: AFFINE,DISCRETE (default)
        --simval        code for determining which similarty measure is used to assess cost during registration: options are 1) SSD; 2) pearsons correlation (default); 3) NMI;)
        --it    number of iterations at each resolution (default -–it=3,3,3)
        --sigma_in      smoothing parameter for input image (default --sigma_in=2,2,2)
        --sigma_ref     Sigma parameter - smoothing parameter for reference image  (set equal to sigma_in by default)
        --lambda        Lambda parameter - controls contribution of regulariser
        --datagrid      DATA grid resolution (default --datagrid=5,5,5). If parameter = 0 then the native mesh is used.
        --CPgrid        Control point grid resolution (default --CPgrid=2,3,4)
        --SGgrid        Sampling grid resolution (default = 2 levels higher than the control point grid)
        --anatgrid      Anatomical grid resolution (default = 2 levels higher than the control point grid)
        --aKNN  Number of neighbours for estimation of kNN graph and alpha entropy measure (default --aKNN=5,5,5)
        --cutthr        Upper and lower thresholds for defining cut vertices (default --cutthr=0,0)
        --mInt  Method used for mesh interpolations, options: TPS or BARY (default)
        --dInt  Method used for data interpolations, options: GAUSSIAN or ADAP_BARY (default)
        --regexp        Regulariser exponent 'rexp' (default 2.0)
        --weight        weight regulariser cost using areal distortion weighting
        --anorm norm regulariser cost using mean angle (for HCP compatibility)
        --rescaleL      rescale label grid rather than using barycentres
        --log   log transform and normalise the data
        --IN    Normalize intensity ranges using histogram matching
        --INc   Normalize intensity ranges using histogram matching excluding cut
        --VN    Variance normalize data
        --scale Scale intensity ranges of a features in multivariate data to be equal to that of the first (useful for multimodal contrasts)
        --excl  Ignore the cut when resampling the data
        --stepsize      gradient stepping for affine optimisation (default 0.01)
        --gradsampling  Determines the finite distance spacing for the affine gradient calculation (default 0.5)
        --numthreads    number of threads for tbb (default 1)

--regoption: Option doesn't exist!
@                                                                   
Thu Jul 16 16:24:36 EDT 2020:FreeSurfer2CaretConvertAndRegisterNonlinear.sh: While running '/mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh /mnt/hcp01/scR21_HCP4_2_MSMSulc 50016 /mnt/hcp01/scR21_HCP4_2_MSMSulc/50016/T1w /mnt/hcp01/scR21_HCP4_2_MSMSulc/50016/MNINonLinear Native /mnt/hcp01/scR21_HCP4_2_MSMSulc/50016/T1w/50016 T1w_acpc_dc_restore_1mm T1w_acpc_dc_restore T2w_acpc_dc_restore /mnt/jxvs01/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/templates/standard_mesh_atlases 164 32 /mnt/hcp01/scR21_HCP4_2_MSMSulc/50016/MNINonLinear/xfms/acpc_dc2standard /mnt/hcp01/scR21_HCP4_2_MSMSulc/50016/MNINonLinear/xfms/standard2acpc_dc T1w_restore T2w_restore brainmask_fs /mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/config/FreeSurferAllLut.txt /mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/templates/91282_Greyordinates 2 /mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/config/FreeSurferSubcorticalLabelTableLut.txt MSMSulc 1':
Thu Jul 16 16:24:36 EDT 2020:FreeSurfer2CaretConvertAndRegisterNonlinear.sh: ERROR: '/mnt/tools/HCP-4.2-Prerequisites/MSM_HOCR-3.0FSL/src/MSM/msm' command failed with return code: 1
Thu Jul 16 16:24:36 EDT 2020:PostFreeSurferPipeline.sh: While running '/mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/PostFreeSurfer/PostFreeSurferPipeline.sh --path=/mnt/hcp01/scR21_HCP4_2_MSMSulc --subject=50016 --surfatlasdir=/mnt/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/templates/standard_mesh_atlases --grayordinatesdir=/mnt/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/templates/91282_Greyordinates --grayordinatesres=2 --hiresmesh=164 --lowresmesh=32 --subcortgraylabels=/mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/config/FreeSurferSubcorticalLabelTableLut.txt --freesurferlabels=/mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/config/FreeSurferAllLut.txt --refmyelinmaps=/mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/global/templates/standard_mesh_atlases/Conte69.MyelinMap_BC.164k_fs_LR.dscalar.nii --regname=MSMSulc --printcom=':
Thu Jul 16 16:24:36 EDT 2020:PostFreeSurferPipeline.sh: ERROR: '/mnt/tools/HCP-4.2-Prerequisites/HCPpipelines-4.2.0/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh' command failed with return code: 1

Can anyone seen this issue before?

Thank you 
Best Regards
Sameera

**Comment by ecr05** [comment]
This is because you are probably using the FSL version instead of this version. Perhaps there is a clash of paths on your computer?

**Comment by sameera2004** [comment]
thanks @ecr05, the issue was source code (tar.gz) is incomplete. Matt Glasser told me to use release before. Later I saw the open issue regarding that (https://github.com/ecr05/MSM_HOCR/issues/13).  Then, I cloned the git repo and complied. 
I was able to use "MSMSulc" to do the surface registration for all our data.

**Comment by ecr05** [comment]
OK, I'm still not following this. I've copied all the source code to a zip file for the release but I'm concerned this is something else. The code should not include the newmesh library as this is no longer compatible with FSLv6 so the code available by cloning the master should be sufficient?

**Comment by sameera2004** [comment]
No zip file is not complete the time I was downloading (12 days ago). Did you upload it again recently ?

**Comment by ecr05** [comment]
Today. Which zip file are you talking about?

**Comment by sameera2004** [comment]
Source code(tar.gz)

**Comment by ecr05** [comment]
I don't know what you mean. Where are you downloading it from?

I've uploaded a copy of the source code to the recent release. Beyond that I don't know how to help. The clone from the master will work when compiled with FSLv6.


Dr Emma C. Robinson


Apologies if you get emails outside normal work hours - I am at home with small children. I don't expect a reply at these times.


Lecturer In Medical Image Analysis

School of Biomedical Engineering and Imaging Sciences

Kings College London


Office: 5th floor, Becket House, 1 Lambeth Palace Road, London SE1 7EU, UK
Mail: 4th Floor, Lambeth Wing, St Thomas' Hospital, London SE1 7EH
Tel. +44 (0)20 784 89557

________________________________

**Comment by sameera2004** [comment]
Hi @ecr05, This is same issue regarding to open issue you had . (https://github.com/ecr05/MSM_HOCR/issues/13). 

If you uploaded zip file again, then it should be fine. I was able to solve my issue and processed my dataset using "MSMSulc".  I thought this will help. Thank you so much.
