### ISSUE TITLE
niftiio, fslio not found

### ISSUE THREAD

**Issue by tashrifbillah** [ecr05/MSM_HOCR#8]
Hey guys,

We are getting the above libraries missing error:

```
[~/Downloads/MSM_HOCR/src/MSM]$ make install
make[1]: Entering directory `/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/MSM_HOCR/src/MSM'
make[2]: Entering directory `/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/MSM_HOCR/src/MSM'
c++ -Wl,-rpath,'$ORIGIN/../lib' -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -lopenblas -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/lib64  -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib   -L. -L/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/fsl_dev_dir/lib  -L/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/fsl_dev_dir/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/lib -L. -L/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/fsl_dev_dir/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/lib -o msm msm.o -lmeshreg -lfastpd -ldiscrete -lnewmeshclass -lfslsurface -lgiftiio -lmm  -lexpat  -lfslvtkio -lnewimage  -lmiscmaths -lmiscplot -lmiscpic -lfslio -lniftiio -lnewmat -lutils  -lbint -lnewran -lprob -lznz -lgdc -lgd -lpng  -lz 
/usr/bin/ld: cannot find -lfslio
/usr/bin/ld: cannot find -lniftiio
collect2: error: ld returned 1 exit status
make[2]: *** [msm] Error 1
make[2]: Leaving directory `/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/MSM_HOCR/src/MSM'
make[1]: *** [master-install-script] Error 2
make[1]: Leaving directory `/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/MSM_HOCR/src/MSM'
make: *** [install] Error 2
```

**Possible fix**

Is this pipeline for FSL 5.0.11? In the stated version, we have both `libfslio.a` and `libniftiio.a` in `${FSLDIR}/lib`, but those libraries probably have been removed in FSL 6.0.1. On the other hand, the [prerequisites](https://github.com/Washington-University/HCPpipelines/wiki/Installation-and-Usage-Instructions#prerequisites) say FSL 6.0.1.

Even if the pipeline is for FSL 5.0.11, you don't have `-L${FSLDIR}/lib` in either of the [USRINCFLAGS and USRLDFLAGS](https://github.com/ecr05/MSM_HOCR/blob/master/src/MSM/Makefile#L8). For the compiler to be able to find them, we should link `${FSLDIR}/lib` directory as well (similar for include).

**Comment by ecr05** [comment]
Sorry  - just seen this. Will get back to you asap

**Comment by ecr05** [comment]
Should work now? Please let me know if you have any further problems

**Comment by ecr05** [comment]
> Hey guys,
> 
> We are getting the above libraries missing error:
> 
> ```
> [~/Downloads/MSM_HOCR/src/MSM]$ make install
> make[1]: Entering directory `/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/MSM_HOCR/src/MSM'
> make[2]: Entering directory `/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/MSM_HOCR/src/MSM'
> c++ -Wl,-rpath,'$ORIGIN/../lib' -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -lopenblas -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/lib64  -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/extras/lib   -L. -L/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/fsl_dev_dir/lib  -L/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/fsl_dev_dir/extras/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/lib -L. -L/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/fsl_dev_dir/lib -L/rfanfs/pnl-zorro/software/pnlpipe3/fsl/lib -o msm msm.o -lmeshreg -lfastpd -ldiscrete -lnewmeshclass -lfslsurface -lgiftiio -lmm  -lexpat  -lfslvtkio -lnewimage  -lmiscmaths -lmiscplot -lmiscpic -lfslio -lniftiio -lnewmat -lutils  -lbint -lnewran -lprob -lznz -lgdc -lgd -lpng  -lz 
> /usr/bin/ld: cannot find -lfslio
> /usr/bin/ld: cannot find -lniftiio
> collect2: error: ld returned 1 exit status
> make[2]: *** [msm] Error 1
> make[2]: Leaving directory `/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/MSM_HOCR/src/MSM'
> make[1]: *** [master-install-script] Error 2
> make[1]: Leaving directory `/rfanfs/pnl-zorro/projects/U01_HCP_Psychosis/HCPPipeline/MSM_HOCR/src/MSM'
> make: *** [install] Error 2
> ```
> 
> **Possible fix**
> 
> Is this pipeline for FSL 5.0.11? In the stated version, we have both `libfslio.a` and `libniftiio.a` in `${FSLDIR}/lib`, but those libraries probably have been removed in FSL 6.0.1. On the other hand, the [prerequisites](https://github.com/Washington-University/HCPpipelines/wiki/Installation-and-Usage-Instructions#prerequisites) say FSL 6.0.1.
> 
> Even if the pipeline is for FSL 5.0.11, you don't have `-L${FSLDIR}/lib` in either of the [USRINCFLAGS and USRLDFLAGS](https://github.com/ecr05/MSM_HOCR/blob/master/src/MSM/Makefile#L8). For the compiler to be able to find them, we should link `${FSLDIR}/lib` directory as well (similar for include).

**Comment by tashrifbillah** [comment]
@ecr05 

> Should work now?

Are you referring to this [commit](https://github.com/ecr05/MSM_HOCR/commit/6e348e78d3003ce28b9ba2c2a8c7cadd773e713d) ?

Can we keep the issue open until we get back to you?

**Comment by ecr05** [comment]
Yes.

**Comment by tashrifbillah** [comment]
@vanzod , thanks for verifying the commit. Between the time I opened this issue and fix was given, my folks move on to other solution. So I didn't get a chance to test it.

@ecr05 feel free to close this issue.

**Comment by ecr05** [comment]
@vanzod - sorry for the delay but just to let you know I have finally got round to building those binaries - thanks for the suggestion
